// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CC_Sports.Models
{
    [Table("Invoice")]
    public partial class Invoice
    {
        [Key]
        [Column("InvoiceID")] //OrderDetailPK
        public int InvoiceId { get; set; }

        [Column("OrderIDFK")] //OrderFK
        public int OrderIdfk { get; set; }

        [Column("ProductIDFK")] //ProductFK
        public int ProductIdfk { get; set; }
        public int OrderQty { get; set; }

        [ForeignKey(nameof(OrderIdfk))]
        [InverseProperty(nameof(Order.Invoices))]
        public virtual Order OrderIdfkNavigation { get; set; }
        [ForeignKey(nameof(ProductIdfk))]
        [InverseProperty(nameof(Product.Invoices))]
        public virtual Product ProductIdfkNavigation { get; set; }
    }
}