// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CC_Sports.Models
{
    [Table("Order")]
    public partial class Order
    {
        public Order()
        {
            Invoices = new HashSet<Invoice>();
        }

        [Key]
        [Column("OrderID")]
        public int OrderId { get; set; }

        [Column("UserID")]
        public int UserId { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime OrderDate { get; set; }
        [StringLength(50)]
        public string ShipFirstName { get; set; }
        [StringLength(50)]
        public string ShipLastName { get; set; }
        [StringLength(100)]
        public string ShipAddress { get; set; }
        [StringLength(50)]
        public string ShipCity { get; set; }
        [StringLength(5)]
        public string ShipState { get; set; }
        [StringLength(10)]
        public string ShipZip { get; set; }
        [Column(TypeName = "decimal(7, 2)")]
        public decimal TotalPrice { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("Orders")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(Invoice.OrderIdfkNavigation))]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}