// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CC_Sports.Models
{
    [Table("Product")]
    public partial class Product
    {
        public Product()
        {
            Invoices = new HashSet<Invoice>();
        }

        [Key]
        [Column("ProductID")]
        public int ProductId { get; set; }

        [Column("BrandID")]
        public int BrandId { get; set; }

        [Required]
        [StringLength(20)]
        public string Brand { get; set; }

        [Required]
        [StringLength(20)]
        public string Model { get; set; }

        [StringLength(1)]
        public string Gender { get; set; }

        [Required]
        [StringLength(12)]
        public string Sport { get; set; }

        [StringLength(15)]
        public string Conditions { get; set; }

        [Column(TypeName = "decimal(7, 2)")]
        public decimal? UnitPrice { get; set; }

        [StringLength(50)]
        public string Image { get; set; }


        [Required]
        [Column(TypeName = "ntext")]
        public string Description { get; set; }

        [ForeignKey(nameof(BrandId))]
        [InverseProperty("Products")]
        public virtual Brand BrandNavigation { get; set; }

        [InverseProperty(nameof(Invoice.ProductIdfkNavigation))]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}